home:
    pattern:  /
    defaults: { _controller: ProlongUserBundle:Default:index, _format: ~ }

api:
    type: rest
    prefix: /api/v1
    resource: "@ProlongUserBundle/Resources/config/rest_routes.yml"
admin_api:
    type: rest
    prefix: /api/v1/admin
    resource: "@ProlongUserBundle/Resources/config/rest_admin_routes.yml"
