parameters:
    ROLE_ADMIN : ROLE_ADMIN
    ROLE_CUSTOMER : ROLE_CUSTOMER

security:
    encoders:
        Prolong\UserBundle\Entity\User: sha512

    providers:
        main:
          entity:
              class: Prolong\UserBundle\Entity\User
              property: email


    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/api/v[0-9]+/admin/, roles: ROLE_ADMIN }

        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    firewalls:
        main:
            pattern: ^/
            security: true
            anonymous: ~

            form_login:
                # field names for the username and password fields
                username_parameter: login[email]
                password_parameter: login[password]

                check_path: /login_check
                login_path: /login

            logout:
                path: user.logout
                target: /

            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                always_remember_me: true
                path:     /
